version: '3.3'
services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
    kafka-node-1:
        image: wurstmeister/kafka
        # image: nyadesu/kafka-docker
        container_name: kafka-node-1
        depends_on:
            - zookeeper
        ports:
            - "2181:2181"
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_HOST_NAME: localhost
            ADVERTISED_PORT: 9092
            ADVERTISED_HOST_NAME: localhost
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
